blockworks-foundation/mango-v4

programs/mango-v4/src/instructions/perp_settle_fees.rs, programs/mango-v4/src/instructions/perp_settle_pnl.rs
It's likely for perp pnl to oscillate and be settled in positive and negative direction repeatedly. If the user's USDC balance is <= 0, every settlement of negative pnl will increase borrows and cause loan origination fees.
Over time the fees accumulated this way could be significant. Skipping loan origination fees for borrows created from perp settlement avoids that.
=> Perp: settlement applies no loan origination fee

.github/workflows/ci-code-review-rust.yml, Cargo.lock, client/Cargo.toml, client/src/account_fetcher.rs, client/src/chain_data_fetcher.rs, client/src/client.rs
This required redoing the cached account fetcher logic to properly deal with locking and repeated calls while a fetch is ongoing.
=> rust client: Make AccountFetcher futures Send

.github/workflows/ci-code-review-ts.yml, .github/workflows/ci-dependency-scan-cargo.yml, .github/workflows/ci-dependency-scan-yarn.yml
This PR changes outputs from dependency and TS code scanning tools from the runner to the security tab
Makes it easier to track non-critical vulnerabilities and enables us to easily ignore etc. with audit trail.
=> output to security tab

client/src/perp_pnl.rs, programs/mango-v4/src/instructions/perp_liq_quote_and_bankruptcy.rs, programs/mango-v4/src/instructions/perp_settle_fees.rs, programs/mango-v4/src/instructions/perp_settle_pnl.rs, programs/mango-v4/src/state/mango_account_components.rs, programs/mango-v4/tests/test_liq_perps.rs, programs/mango-v4/tests/test_perp.rs, programs/mango-v4/tests/test_perp_settle.rs, ts/client/src/accounts/healthCache.spec.ts, ts/client/src/accounts/mangoAccount.ts, ts/client/src/mango_v4.ts, ts/client/src/scripts/mm/taker.ts
This includes trade pnl, funding and fees. Tracking this makes it easier for uis to display a consistent position overall pnl value that doesn't decrease by settling.
=> Perps: track overall realized pnl relating to a position

package.json, ts/client/src/accounts/bank.ts, ts/client/src/accounts/group.ts, ts/client/src/accounts/oracle.ts, ts/client/src/accounts/perp.ts
Parses the best value we have for last updated slot and sets it on the Bank and PerpMarkets when reloading oracle prices. Used for checking oracle staleness on the client side.
=> Add oracleLastUpdatedSlot to Bank and PerpMarket

ts/client/src/accounts/mangoAccount.ts, ts/client/src/accounts/perp.ts, ts/client/src/client.ts, ts/client/src/scripts/mm/log-perp-ob.ts, ts/client/src/scripts/mm/market-maker.ts, ts/client/src/scripts/mm/taker.ts
Serum OO accounts are needed to do a full health computation. But these are only loaded via mango account reload or reloadAccountData methods. Now this side effect is already achievable while fetching the mango account with an explicity flag. Also reloadAccountData is renamed to be more specific, since we dont really load any other data
=> fix bug where serum oo where not loaded

programs/mango-v4/tests/cases/mod.rs, programs/mango-v4/tests/cases/test_alt.rs, programs/mango-v4/tests/cases/test_bankrupt_tokens.rs, programs/mango-v4/tests/cases/test_basic.rs, programs/mango-v4/tests/cases/test_benchmark.rs, programs/mango-v4/tests/cases/test_borrow_limits.rs, programs/mango-v4/tests/cases/test_delegate.rs, programs/mango-v4/tests/cases/test_health_compute.rs, programs/mango-v4/tests/cases/test_health_region.rs, programs/mango-v4/tests/cases/test_ix_gate_set.rs, programs/mango-v4/tests/cases/test_liq_perps.rs, programs/mango-v4/tests/cases/test_liq_tokens.rs, programs/mango-v4/tests/cases/test_margin_trade.rs, programs/mango-v4/tests/cases/test_perp.rs, programs/mango-v4/tests/cases/test_perp_settle.rs, programs/mango-v4/tests/cases/test_perp_settle_fees.rs, programs/mango-v4/tests/cases/test_position_lifetime.rs, programs/mango-v4/tests/cases/test_reduce_only.rs, programs/mango-v4/tests/cases/test_serum.rs, programs/mango-v4/tests/cases/test_token_update_index_and_rate.rs, programs/mango-v4/tests/program_test/cookies.rs, programs/mango-v4/tests/program_test/mango_client.rs, programs/mango-v4/tests/program_test/serum.rs, programs/mango-v4/tests/program_test/solana.rs, programs/mango-v4/tests/test_all.rs
Speeds up the linking step, needs way less disk space for test binaries and executes tests significantly faster.
Test execution went from 35s -> 29s for me and compilation improved a lot.
=> Create a single rust test binary

programs/mango-v4/src/instructions/perp_liq_base_or_positive_pnl.rs, programs/mango-v4/src/instructions/token_liq_with_token.rs, programs/mango-v4/tests/cases/test_liq_perps_positive_pnl.rs
Previously liquidation would overestimate the amount required, because it used the oracle price for computing the health gain from liquidation.
Now it uses the correct (stable price adjusted) price for figuring out the amount of liquidation required, while still executing at fee-adjusted oracle price.
=> Liquidation: Fix amounts when stable price != oracle price

.github/labeler.yml
Minor change to broaden the previous 'ci' PR label to encompass all DevOps'y changes
=> change 'ci' to 'devops' label

programs/mango-v4/src/health/cache.rs, programs/mango-v4/src/health/client.rs, programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/instructions/health_region.rs, programs/mango-v4/src/instructions/perp_liq_base_or_positive_pnl.rs, programs/mango-v4/src/instructions/perp_liq_force_cancel_orders.rs, programs/mango-v4/src/instructions/perp_liq_negative_pnl_or_bankruptcy.rs, programs/mango-v4/src/instructions/perp_place_order.rs, programs/mango-v4/src/instructions/perp_settle_pnl.rs, programs/mango-v4/src/instructions/serum3_liq_force_cancel_orders.rs, programs/mango-v4/src/instructions/serum3_place_order.rs, programs/mango-v4/src/instructions/token_deposit.rs, programs/mango-v4/src/instructions/token_liq_bankruptcy.rs, programs/mango-v4/src/instructions/token_liq_with_token.rs, programs/mango-v4/src/instructions/token_withdraw.rs, programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/src/accounts/bank.ts, ts/client/src/accounts/healthCache.ts, ts/client/src/accounts/mangoAccount.ts, ts/client/src/mango_v4.ts
Due to the safety features in v4, the init health can differ from maint health a lot more than it used to in v3. This is because of stable-price adjusted oracle prices used in init health, and the weight scaling based on total deposits and borrows used in init health.
The effect is that once an account becomes liquidatable, it could be liquidated a lot until it reaches init>=0.
The original idea of liquidating until init>=0 was just to provide some buffer, such that liquidated accounts wouldn't immediately become liquidatable again.
This patch decouples the buffer idea explicit from init health by creating a new LiquidationEnd health type. Liquidation proceeds until the LiquidationEnd health becomes positive.
=> Change liquidation end target to a new, third health type

Cargo.lock, cli/src/main.rs, client/Cargo.toml, client/src/account_update_stream.rs, client/src/client.rs, client/src/lib.rs, client/src/snapshot_source.rs, client/src/util.rs, client/src/websocket_source.rs, keeper/src/main.rs, liquidator/src/main.rs, liquidator/src/rebalance.rs, liquidator/src/util.rs
- move actual liquidation to a separate thread from updating the chain_data
- make it easier to reuse liquidator logic for the upcoming settle-bot
=> Improvements to liquidator and client

programs/mango-v4/src/instructions/perp_edit_market.rs, programs/mango-v4/src/instructions/token_edit.rs
This allows the security council to say "users can't create new borrows against this token/perp anymore". In some emergency situations this can help reduce risk exposure.
For example, if the price of a wrapped asset permanently depegs from its underlying or there is a successful long-term attack on an oracle, this (and reduce-only) would significantly reduce exploitability until the DAO's decision for how to resolve the issue goes through.
=> Security admin: Allow disabling token/perp init collateral

programs/mango-v4/src/instructions/perp_place_order.rs, programs/mango-v4/src/state/mango_account_components.rs
The previous strict behavior of taking existing open orders into account is only used when the perp market itself is also flagged as reduce-only.
=> Perp: User-selected reduce-only behaves more intuitively

Cargo.lock, bin/cli/Cargo.toml, bin/keeper/Cargo.toml, bin/liquidator/Cargo.toml, bin/settle-bot/Cargo.toml, lib/client/Cargo.toml, programs/mango-v4/Cargo.toml, programs/mango-v4/src/accounts_ix/token_register.rs, programs/mango-v4/src/health/cache.rs, programs/mango-v4/src/health/client.rs, programs/mango-v4/src/instructions/benchmark.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/state/bank.rs
Should also review the top commit on https://gitlab.com/ckamm/fixed/-/commits/v1.11.0-mango/ which is backported from https://gitlab.com/ckamm/fixed/-/commits/v1.23.0-mango
=> Downgrade the `fixed` crate to v1.11.0

lib/client/src/gpa.rs
basically seeing a lot of this - Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`. 
Found this https://github.com/solana-labs/solana/pull/28499
=> workaround where rpc rejects base58 encoded pubkeys

programs/mango-v4/src/instructions/perp_create_market.rs, programs/mango-v4/src/instructions/token_liq_bankruptcy.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/state/group.rs, programs/mango-v4/tests/cases/test_bankrupt_tokens.rs
Previously a token from the insurance fund was valued at 1 USD. Now it uses the oracle associated with it (USDC oracle).
=> token_liq_bankruptcy: Use oracle for valuing insurance fund tokens

programs/mango-v4/src/instructions/token_update_index_and_rate.rs, programs/mango-v4/src/state/perp_market.rs
Previously, if the funding or interest updating instruction wasn't called for a long time (like for a solana downtime or the security council halting the program), the next update would apply funding or interest for the whole time interval since the last update.
This could lead to a bad downtime situation becoming worse. Instead, limit the maximum funding and interest time interval to one hour.
=> Limit funding and interest accrual during downtimes

ts/client/src/accounts/mangoAccount.ts
Attempting to settle Perp PnL in the UI results in RPC ratelimiting. This is caused by many getMultipleAccounts calls with no addresses in the params. We should check if there's any active spot markets before making the gMA call.
=> Don't reload OpenOrders if there's no active markets

programs/mango-v4/src/health/cache.rs, programs/mango-v4/src/health/client.rs, programs/mango-v4/src/instructions/account_buyback_fees_with_mngo.rs, programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/instructions/perp_liq_base_or_positive_pnl.rs, programs/mango-v4/src/instructions/perp_liq_negative_pnl_or_bankruptcy.rs, programs/mango-v4/src/instructions/perp_settle_fees.rs, programs/mango-v4/src/instructions/perp_settle_pnl.rs, programs/mango-v4/src/instructions/serum3_place_order.rs, programs/mango-v4/src/instructions/token_liq_bankruptcy.rs, programs/mango-v4/src/instructions/token_liq_with_token.rs, programs/mango-v4/src/instructions/token_withdraw.rs, programs/mango-v4/src/state/bank.rs, programs/mango-v4/tests/cases/test_borrow_limits.rs, programs/mango-v4/tests/cases/test_perp_settle_fees.rs
That way it's easier to be specific about where the limit should be checked.
=> Net borrow limit: Separate out tracking and checking

programs/mango-v4/src/instructions/token_liq_with_token.rs, programs/mango-v4/tests/cases/test_bankrupt_tokens.rs, programs/mango-v4/tests/cases/test_liq_tokens.rs, programs/mango-v4/tests/cases/test_perp_settle_fees.rs
> It might lead to bad incentives to sum up the liq fees like this. Example: Liquidating SOL with USDC gives liqors a 5% liq fee, but liquidating SOL with USDT gives them 7.5%...
=> Don't incentivise using asset tokens with high liquidation fee during liquidation

lib/client/src/client.rs, mango_v4.json, programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/src/client.ts, ts/client/src/mango_v4.ts
It looks like it wasn't possible to exploit the program by re-initializing the user-owned token accounts used in flash loan because the later use of health_ais with the health computation would error out if any token account was included there.
However, the check and a few others were too indirect. In this patch:
- We explicitly pass the number of loans into FlashLoanEnd (verified from FlashLoanBegin)
- Add explicit checks for token mints, so it's no longer possible to use token accounts for forein mints in Begin when the loan amount is zero, and it's clearer to see that the bookkeeping in End won't break if the user reinited the account for a different mint.
- Also add a few other extra comments and checks.
The updated FlashLoanEnd instruction is called FlashLoanEndV2
=> FlashLoan: Don't deduce vault_len, add more checks

programs/mango-v4/src/instructions/ix_gate_set.rs, programs/mango-v4/tests/cases/test_ix_gate_set.rs, programs/mango-v4/tests/program_test/mango_client.rs
The bug allowed the security admin to enable instructions. This was supposed to require the group admin.
=> IxGate: Fix check for re-enabling instructions

ts/client/scripts/param-check.ts
```
COIN,    Scale, Liq Fee, $->coin, coin-$
BONK,  $100000, 20.000%, 22.24%, 10.41%
MNGO,    $5000, 20.000%, 21.35%, 21.38%
SOL, $5000000,  5.000%, 60.44%, 60.44%
wBTC (Portal),  $100000,  5.000%, 2.94%, 9.67%
MSOL, $1000000,  5.000%, 91.75%, 6.04%
ETH (Portal),  $100000,  5.000%, 0.56%, 51.91%
USDT, $1000000,  2.500%, 10.44%, 0.08%
✨  Done in 11.92s.
```
Basically this script shows the price impact of swapping deposit or borrow quote scale limit from and to usdc. Purpose is to quickly see if the scales are too lax
=> Script to check token params for risk

ts/client/src/client.ts, ts/client/src/utils/rpc.ts
* Refactor code for collecting health accounts, 
* Remove scanning retriever, only build accounts for fixed retriever because they should always works, saves having to maintain 2 code blocks
* fix bug where bank oracle was skipped while closing account if same perp position in a market with same oracle was also deactivated earlier in same tx
Tested on mainnet so - via UI, created an account, deposited sol and usdc, opened perp and spot market positions, closed perp position, settled perp and spot, then called clients emptyAndCloseMangoAccount on dev and this branch, breaks on dev (https://explorer.solana.com/tx/3Wgf6GVtCYXVT3D3H1MK5TtEroKt3wYrdtnBgRNWH9JY2yvfLyov8dRUY5K7ukT8VPHJmGKovLEiLii59AV1zgNa), works on this branch (https://explorer.solana.com/tx/4Y8sVCxKxo3SwwRt1Kjc9zvk63cypbkqQd2cb …
=> Fix bug in closing mango account

programs/mango-v4/src/instructions/token_register_trustless.rs
Previously tokens listed this way could be borrowed. Now tokens start with reduce-only set to the "no borrows" mode.
Also decrease the default soft borrow/deposit limits significantly, even if they don't come into effect when there are no borrows and the deposit weight is 0 anyway.
=> token_register_trustless: Disable borrowing by default

programs/mango-v4/src/error.rs, programs/mango-v4/src/health/account_retriever.rs
When an invalid number of accounts is passed in, which is one of the most common error messages new integrators will see.
=> Improve error message for FixedAccountRetriever

programs/mango-v4/src/instructions/serum3_liq_force_cancel_orders.rs, programs/mango-v4/src/instructions/serum3_settle_funds.rs, programs/mango-v4/src/instructions/token_liq_bankruptcy.rs, programs/mango-v4/src/instructions/token_liq_with_token.rs, programs/mango-v4/src/instructions/token_withdraw.rs, programs/mango-v4/src/logs.rs
For performance reasons it is desirable to have prices logged in the WithdrawLoanLog.
I am using the same event (not incrementing it) as I hope this can be merged before the previous WithdrawLoanLog event is deployed.
=> Add price to WithdrawLoanLog

programs/mango-v4/src/error.rs, programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/tests/cases/test_perp.rs, programs/mango-v4/tests/cases/test_serum.rs
Instead of requiring a strict increase when init health < 0.
This allows users to still place reducing limit orders on the spot and perp orderbooks as long as these orders keep the health unchanged.
=> Health: Allow actions while init health does not decrease

programs/mango-v4/src/instructions/perp_create_market.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/instructions/token_register_trustless.rs, programs/mango-v4/src/state/stable_price.rs
This helps when listing tokens or perp markets with an upcoming oracle. Currently the stable price would be 0 and would need to be manually reset by DAO proposal.
With this change, the first non-zero value will be used as the starting point for the stable price instead.
=> Stable Price: Reset on first price != 0

programs/mango-v4/src/instructions/token_liq_bankruptcy.rs
This makes it easier to debug, since we know what value did not match the requirements.
=> Token bankruptcy: Separate checks

programs/mango-v4/src/instructions/flash_loan.rs
Check for missing banks _before_ checking for "exactly two token changes" because the missing banks can be a cause of the latter error.
=> Flash loan: Better errors for missing banks

ts/client/src/client.ts
Using `SystemProgram.createAccountWithSeed` instead of `SystemProgram.createAccount` eliminates the need in an ephemeral signer for the the wrapping SOL transaction. 
This makes the transaction compatible with Smart Wallets that use delayed transaction execution mechanism, e.g. Fuse Wallet
For more in-depth explanation see section "Ephemeral Signers" here: https://fusedocs.framer.website/docs/fuse-intergration-for-app-devs
=> Client: use createWithSeed when wrapping SOL

programs/mango-v4/src/instructions/token_conditional_swap_trigger.rs
previously we were logging native amount, which does not match other `TokenBalanceLog`s
=> use indexed position in token conditional balance logs

mango_v4.json, programs/mango-v4/src/instructions/account_create.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/src/mango_v4.ts
This one allows specifying the number of tcs slots. That way accounts can be created without needing a separate extend instruction afterwards.
=> Add account_create_v2 instruction

programs/mango-v4/src/instructions/flash_loan.rs
This lifts an unnecessary restriction, making it possible to do things like flash loan and then liquidate with the resulting balances in a single transaction.
The "no mango ix after FlashLoanEnd" limitation was unnecessary: After the flash loan ends, the mango accounts are in a valid state again. And it's impossible to use a two FlashLoanEnd for a single FlashLoanBegin for the same reason that isolated FlashLoanEnds are rejected.
=> FlashLoan: Allow mango ix after flash loan end

programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/tests/cases/test_bankrupt_tokens.rs, programs/mango-v4/tests/cases/test_basic.rs, programs/mango-v4/tests/cases/test_health_compute.rs, programs/mango-v4/tests/cases/test_liq_perps_bankruptcy.rs, programs/mango-v4/tests/cases/test_liq_tokens.rs, programs/mango-v4/tests/cases/test_margin_trade.rs, programs/mango-v4/tests/cases/test_position_lifetime.rs, programs/mango-v4/tests/cases/test_token_conditional_swap.rs, programs/mango-v4/tests/program_test/mango_client.rs, programs/mango-v4/tests/program_test/mango_setup.rs, ts/client/scripts/create-gov-ix.ts, ts/client/src/client.ts
Because of the 64-accounts-per-tx limit. Making a single account use more than half of these could be problematic.
=> Restrict account growth

lib/client/src/client.rs, programs/mango-v4/src/accounts_ix/account_create.rs, programs/mango-v4/src/instructions/account_create.rs, programs/mango-v4/src/instructions/account_expand.rs, programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/tests/cases/test_basic.rs, programs/mango-v4/tests/cases/test_health_compute.rs, programs/mango-v4/tests/cases/test_token_conditional_swap.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/src/client.ts
If the account was previously resized to larger than is allowed now, don't fail unrelated resizes.
=> Account size: Don't fail on unrelated resize

CHANGELOG.md, mango_v4.json, programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/instructions/token_edit.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/instructions/token_register_trustless.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/src/logs.rs, programs/mango-v4/src/state/bank.rs, programs/mango-v4/tests/cases/test_margin_trade.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/scripts/create-gov-ix.ts, ts/client/src/accounts/bank.ts, ts/client/src/client.ts, ts/client/src/clientIxParamBuilder.ts, ts/client/src/mango_v4.ts
- Rename the new "swap fee" to "deposit fee" and let it apply to all deposits, not just for Swap-type flash loans.
- But don't apply it to withdrawals (effectively giving rebates!)
Result of audit feedback
=> FlashLoan: fee fixes

programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/logs.rs
Previously only the part of the approved amount that was a loan got logged, missing some interesting information.
=> FlashLoan: Log the approved amount

programs/mango-v4/src/instructions/token_deposit.rs, programs/mango-v4/tests/cases/test_stale_oracles.rs
This avoids making an account accidentally or intentionally unusable (except for deposits/withdraws) by depositing a token with a stale oracle.
=> Token deposit: Require valid oracle for new token positions

lib/client/src/websocket_source.rs
The serum StreamMap exiting aborts the whole streaming job.
=> Client: fix issue when no serum program is registered

.github/workflows/ci-code-review-rust.yml
fixed the toolchain error:
> error: toolchain 'bpf' is not installed
[this](https://github.com/blockworks-foundation/mango-v4/actions/runs/6429864208/job/17459735418) is the working workflow run
=> fix build-sbf by using "+solana" toolchain

programs/mango-v4/src/health/cache.rs, programs/mango-v4/tests/cases/test_health_compute.rs
This saves around 1/3rd of the compute for active serum markets.
=> serum health: use lower-precision division

mango_v4.json, programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/instructions/token_edit.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/instructions/token_register_trustless.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/src/logs.rs, programs/mango-v4/src/state/bank.rs, programs/mango-v4/tests/cases/test_margin_trade.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/scripts/create-gov-ix.ts, ts/client/src/accounts/bank.ts, ts/client/src/client.ts, ts/client/src/clientIxParamBuilder.ts, ts/client/src/mango_v4.ts
Which applies to the in token amount of swaps only.
Charging a deposit fee on flash loans was a bad idea:
- It incentivizes flash loan users to make the deposit a separate instruction, defeating the purpose.
- For swaps, it makes traders pay a loan origination fee in in-token and a deposit fee in out-token, leading to more complex bookkeeping and ui display.
Instead, charge a fee on the in-token for all flash loans explicitly marked as swaps only.
=> FlashLoan: Replace deposit fee by "swap fee"

mango_v4.json, programs/mango-v4/src/accounts_ix/token_register_trustless.rs, programs/mango-v4/src/instructions/group_edit.rs, programs/mango-v4/src/instructions/token_register_trustless.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/src/state/group.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/src/client.ts, ts/client/src/mango_v4.ts
To avoid potential abuse of fast listing while even when the dao is unresponsive.
=> Group: Limit fast-listing tokens per week

bin/liquidator/src/liquidate.rs, bin/liquidator/src/trigger_tcs.rs, bin/settler/src/settle.rs, bin/settler/src/tcs_start.rs, lib/client/src/client.rs, lib/client/src/context.rs, lib/client/src/health_cache.rs, lib/client/src/jupiter/v4.rs, lib/client/src/jupiter/v6.rs, lib/client/src/util.rs, programs/mango-v4/tests/cases/test_perp.rs, programs/mango-v4/tests/cases/test_serum.rs, programs/mango-v4/tests/program_test/mango_client.rs
Many instructions now return PreparedInstructions instead of a direct Instruction or Vec<Instruction>. That way they can keep track of the expected cu cost of the instructions for the compute limit instruction that gets added once all instructions are made.
=> rust client: ix cu limits based on health compute cost

Cargo.lock, Cargo.toml, bin/cli/Cargo.toml, bin/cli/src/main.rs, bin/cli/src/save_snapshot.rs, programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/src/state/mango_account_components.rs, programs/mango-v4/src/state/mint_info.rs, programs/mango-v4/src/state/oracle.rs, programs/mango-v4/src/state/perp_market.rs, programs/mango-v4/src/state/stable_price.rs
wip: needs to get rid of overridden mango-feeds-connector
=> cli: save-snapshot command

programs/mango-v4/src/health/cache.rs
Growing these vectors is a waste, rough measurements say this saves around 1k bytes for a 5 tokens and 4 serum account.
=> Reduce HealthCache heap use

programs/mango-v4/src/accounts_ix/token_add_bank.rs
It was unused for a long time and it should be reevaluated before being used.
=> Disable TokenAddBank instruction

programs/mango-v4/src/instructions/token_register_trustless.rs
This mostly reverts commit 33bc278a2ca78bf37f291abdc1994e0a3670d57a.
=> revert trustless token registration params to conservative defaults

bin/cli/src/save_snapshot.rs, bin/cli/src/test_oracles.rs, bin/keeper/src/crank.rs, bin/keeper/src/taker.rs, bin/liquidator/src/liquidate.rs, bin/liquidator/src/main.rs, bin/liquidator/src/rebalance.rs, bin/liquidator/src/token_swap_info.rs, bin/liquidator/src/trigger_tcs.rs, bin/liquidator/src/util.rs, bin/service-mango-crank/src/main.rs, bin/service-mango-fills/src/main.rs, bin/service-mango-orderbook/src/main.rs, bin/service-mango-pnl/src/main.rs, bin/settler/src/main.rs, bin/settler/src/settle.rs, bin/settler/src/tcs_start.rs, lib/client/src/client.rs, lib/client/src/context.rs, lib/client/src/jupiter/v4.rs, lib/client/src/jupiter/v6.rs, lib/client/src/lib.rs
- Don't just restart on new listings, but also on significant changes to old listings such as oracle changes.
- Cover the liquidator and settler in addition to the keeper.
=> bins: Fix restarting on new or changed listings

bin/liquidator/src/liquidate.rs, bin/liquidator/src/trigger_tcs.rs, bin/liquidator/src/util.rs, mango_v4.json, programs/mango-v4/src/error.rs, programs/mango-v4/src/health/client.rs, programs/mango-v4/src/instructions/flash_loan.rs, programs/mango-v4/src/instructions/serum3_place_order.rs, programs/mango-v4/src/instructions/token_conditional_swap_start.rs, programs/mango-v4/src/instructions/token_conditional_swap_trigger.rs, programs/mango-v4/src/instructions/token_deposit.rs, programs/mango-v4/src/instructions/token_edit.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/instructions/token_register_trustless.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/src/state/bank.rs, programs/mango-v4/tests/cases/test_basic.rs, programs/mango-v4/tests/cases/test_margin_trade.rs, programs/mango-v4/tests/cases/test_serum.rs, programs/mango-v4/tests/cases/test_token_conditional_swap.rs, programs/mango-v4/tests/program_test/mango_client.rs, programs/mango-v4/tests/program_test/utils.rs, ts/client/src/accounts/bank.ts, ts/client/src/client.ts, ts/client/src/clientIxParamBuilder.ts, ts/client/src/mango_v4.ts
- limit deposits (via deposit, flash loan, tcs)
- limit potential deposits via openbook settle by restricting placable orders via potential_serum_tokens
- introduce Serum3PlaceOrderV2 for this purpose
- account for new limits in liquidator, max_swap
=> Deposit limits

programs/mango-v4/src/instructions/token_register_trustless.rs
- since there's no borrowing or asset weight, don't put staleness or confidence restrictions on the oracle
- disable the tcs fees, they are not enabled anywhere yet
=> adjust token_register_trustless params

programs/mango-v4/src/instructions/perp_cancel_all_orders.rs, programs/mango-v4/src/instructions/perp_cancel_all_orders_by_side.rs, programs/mango-v4/src/instructions/perp_cancel_order.rs, programs/mango-v4/src/instructions/perp_cancel_order_by_client_order_id.rs, programs/mango-v4/src/instructions/perp_consume_events.rs, programs/mango-v4/src/instructions/perp_liq_force_cancel_orders.rs, programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/src/state/mango_account_components.rs, programs/mango-v4/src/state/orderbook/book.rs, programs/mango-v4/src/state/orderbook/queue.rs, programs/mango-v4/tests/cases/test_perp.rs
Previously, freeing would be impossible if a canceling fill or out event was already in-flight - then the order would no longer be on the orderbook.
Now, FillEvent and OutEvent store the order id and can check if the open order slot on the account has been reused already. That allows canceling orders to always free up the user slot immediately.
=> Perp: Always allow users to free perp open order slots

bin/service-mango-orderbook/src/orderbook_filter.rs, programs/mango-v4/src/instructions/token_withdraw.rs, programs/mango-v4/src/state/bank.rs, programs/mango-v4/src/state/oracle.rs, programs/mango-v4/src/state/perp_market.rs
The msg!() caused writes to stdout in the liquidator etc in codepaths that just wanted to check if the oracle was usable.
=> oracle: don't force logging in OracleState functions

package.json, ts/client/scripts/archive/debug-user.ts, ts/client/src/accounts/group.ts, ts/client/src/accounts/healthCache.spec.ts, ts/client/src/accounts/healthCache.ts, ts/client/src/client.ts, ts/client/src/risk.ts, ts/client/src/utils.ts, yarn.lock
This will drop render of some elements on ui from 1.5 sec to few ms  
- To copy something more complicated use fast-copy lib its faster then lodash implementation - e.g group copy
- for health obj its good to use own implementation because we don't need to loop over BN or I80F48 with functions from libs.
Own implementation still do deep copy without reference of given obj.
=> use fast clone

Cargo.lock, Cargo.toml, lib/client/Cargo.toml, lib/client/src/client.rs, lib/client/src/confirm_transaction.rs, lib/client/src/lib.rs, lib/client/src/util.rs
- Allow user configuration of confirmation settings
- Provide a timeout setting, default is 60s
=> Rust client: Revamp transaction confirmation

ts/client/scripts/archive/mb-oracle-inspect.ts, ts/client/src/accounts/group.ts, ts/client/src/accounts/oracle.ts
currently if oracle never reported the price or something with the switchboard oracle is broken, client is starting to break bots and ui. 
Imo it should be catched inside ui or bot that the price is 0 and handled there depending on case, now one broken token breaks use of other tokens as well.
=> fix decoding of broken oracle

mango_v4.json, programs/mango-v4/src/instructions/perp_consume_events.rs, programs/mango-v4/src/instructions/perp_liq_base_or_positive_pnl.rs, programs/mango-v4/src/instructions/perp_liq_negative_pnl_or_bankruptcy.rs, programs/mango-v4/src/instructions/perp_settle_fees.rs, programs/mango-v4/src/instructions/perp_settle_pnl.rs, programs/mango-v4/src/state/mango_account.rs, programs/mango-v4/src/state/mango_account_components.rs, programs/mango-v4/tests/cases/test_liq_perps_bankruptcy.rs, programs/mango-v4/tests/cases/test_liq_perps_base_and_bankruptcy.rs, programs/mango-v4/tests/cases/test_perp_settle.rs, ts/client/src/accounts/mangoAccount.ts, ts/client/src/mango_v4.ts
Previously, we tried to keep track of "other" and "trade" realized pnl. An issue occured when a perp base position went to zero: the way we computed the trade pnl included potential non-trade unsettled pnl.
That caused follow-up trouble because the value could change sign and reset the settle limit for trade pnl.
This change aims to simplify in some ways:
- explicitly talk about oneshot-settleable pnl (fees, funding, liquidation) and recurring-settleable pnl (materialization of settle limit derived from the stable value of the base position when reducing the base position)
- instead of directly tracking realized settleable amounts (which doesn't really work), just decrease the recurring settleable amount when it exceeds the remaining unsettled pnl
- get rid of the directionality to avoid …
=> fix perp settle limit materialization

bin/liquidator/src/liquidate.rs, mango_v4.json, programs/mango-v4/src/error.rs, programs/mango-v4/src/health/cache.rs, programs/mango-v4/src/health/client.rs, programs/mango-v4/src/instructions/token_edit.rs, programs/mango-v4/src/instructions/token_liq_with_token.rs, programs/mango-v4/src/instructions/token_register.rs, programs/mango-v4/src/instructions/token_register_trustless.rs, programs/mango-v4/src/lib.rs, programs/mango-v4/src/state/bank.rs, programs/mango-v4/tests/cases/test_liq_tokens.rs, programs/mango-v4/tests/program_test/mango_client.rs, ts/client/src/accounts/bank.ts, ts/client/src/client.ts, ts/client/src/clientIxParamBuilder.ts, ts/client/src/mango_v4.ts
This removes the oracle dependency for tokens with zero maint asset weight that are not borrowable.
=> liquidation: Disallow liquidating assets with zero maint asset weight

Cargo.lock, bin/cli/src/main.rs, bin/keeper/src/crank.rs, bin/keeper/src/main.rs, bin/keeper/src/taker.rs, bin/liquidator/src/main.rs, bin/liquidator/src/trigger_tcs.rs, bin/settler/src/main.rs, bin/settler/src/settle.rs, lib/client/Cargo.toml, lib/client/src/client.rs, lib/client/src/jupiter/v4.rs, lib/client/src/jupiter/v6.rs, lib/client/src/lib.rs, lib/client/src/priority_fees.rs, lib/client/src/priority_fees_cli.rs
This allows connecting to a lite-rpc feed to receive block priority updates and computing recently good priority fee values based on that.
=> rust client: optionally derive prio fees from feed

bin/cli/src/main.rs, lib/client/src/client.rs, programs/mango-v4/src/state/mango_account.rs
Auto close first unused perp account _if_ it's needed to place a new order because all slots are currently allocated
This is done on the client side because we need health data to be correct on the program side when processing the place order
*Example tx:*
[3j5cZZcmc7MEXwNAsdoWKZRgea8SAXKs5gE2jxuXi2Pzgmxang9ZrgKwTL5fXPHaJchJ1e7wDNobJHSPBdEqpTz3](https://explorer.solana.com/tx/3j5cZZcmc7MEXwNAsdoWKZRgea8SAXKs5gE2jxuXi2Pzgmxang9ZrgKwTL5fXPHaJchJ1e7wDNobJHSPBdEqpTz3)
=> rust client: Perp - Auto close account when needed

bin/cli/src/main.rs, lib/client/src/client.rs
Example tx:
https://explorer.solana.com/tx/FNjZpELFjhqCh9sxcfUNt2YtNTRjkvkWvt7hguAQ4RePKHWcsmrv5PUAvngCECz2BmbRWpod2DESvg6myoKedZK
When placing a new serum3 order, if needed:
1/ try to close unused token to free slots for new order base/quote tokens
2/ try to close unused spot market to free slot for new order
3/ if 1 failed, try again (closing one market reduce token usage count)
4/ try to create the new spot market slot
=> Rust client: auto close spot account if needed to place a new order 

bin/service-mango-health/src/main.rs
This should help with memory issue while running the health monitoring service
=> service-mango-health: use jemalloc

bin/liquidator/src/rebalance.rs
randomly select token/perps for rebalancing to avoid failing at every try if one token is having an issue
=> Liquidator: randomly select token/perps for rebalancing

bin/keeper/src/crank.rs
reporting a "confirmation time" on an error response made the metrics confusing
=> keeper: report confirmation times only on success

bin/liquidator/src/main.rs, bin/liquidator/src/rebalance.rs
- always allow them, now that v0.22 is deployed and delegates can withdraw small token amounts to the owner's ata
- increase the dust amount to $0.001 to avoid issues where the logic is a few lamports off
=> liquidator: fix withdraws on rebalance

lib/client/src/client.rs, lib/client/src/context.rs
Needed that patch to make a liquidator rebalancing works (small amount => withdrawn)
=> rust client: add a CU estimate for token withdrawal

programs/mango-v4/src/instructions/token_withdraw.rs
This is necessary for new liquidator feature of rebalancing using limit orders: 
We need to close the token and market slot so that it's available for new liquidation, but at the same time, it's possible that the min order quantity for a given market is still bigger than allowed max withdrawal.
=> program: remove delegate account withdrawal limit

programs/mango-v4/src/state/orderbook/nodes.rs, programs/mango-v4/src/state/orderbook/ordertree.rs
This ensures casts of local variables don't run into alignment differences.
=> Fix alignment of ordertree nodes

ts/client/scripts/sb-on-demand-crank.ts, ts/client/src/accounts/healthCache.ts
- dont retry oracle updates to prevent writing old state
- submit all oracle updates in parallel to prevent writing old state
- reduce average latency by 1s through prefetching of shared results
- reduce p90 latency by 1m through async refresh of mango group & oracle definitions
- handle promise rejection on tx submission
- improved logging
=> switchboard crank improvements

ts/client/src/accounts/group.ts, ts/client/src/accounts/mangoAccount.ts, ts/client/src/client.ts, ts/client/src/risk.ts
Calculating price impact fails for pairs including USDC, which prevents TCS orders from being created in the UI.
This change uses the available information in the API response, given all tokens are quoted in USDC there, to give correct price impacts for USDC.
New branch based on deploy with commits cherry picked from `pan/fix-usdc-price-impact`
Lint & Test jobs already failing on base branch
=> Fix price impact for USDC pairs
