blockworks-foundation/mango-v4

- ts/client/src/accounts/mangoAccount.ts
> Apply loan origination fee only on loans

- .github/workflows/ci-code-review-rust.yml
- programs/mango-v4/src/health/cache.rs
- programs/mango-v4/src/instructions/group_toggle_halt.rs
- programs/mango-v4/src/instructions/perp_edit_market.rs
- programs/mango-v4/src/instructions/perp_liq_base_position.rs
- programs/mango-v4/src/instructions/perp_liq_quote_and_bankruptcy.rs
- programs/mango-v4/src/instructions/perp_settle_pnl.rs
- programs/mango-v4/src/instructions/serum3_register_market.rs
- programs/mango-v4/src/instructions/token_edit.rs
- programs/mango-v4/src/instructions/token_liq_with_token.rs
- programs/mango-v4/src/instructions/token_register.rs
- programs/mango-v4/src/instructions/token_register_trustless.rs
- programs/mango-v4/src/instructions/token_update_index_and_rate.rs
- programs/mango-v4/src/state/bank.rs
- programs/mango-v4/src/state/mango_account.rs
- programs/mango-v4/src/state/orderbook/bookside_iterator.rs
- programs/mango-v4/src/state/orderbook/ordertree.rs
- programs/mango-v4/src/state/orderbook/ordertree_iterator.rs
- programs/mango-v4/src/state/perp_market.rs
`cargo clippy --no-deps -- -A clippy::result_large_err -A clippy::derive_partial_eq_without_eq`
Doesnt fix all, but fixes most, these are the remaining, 
> fix clippy

- ts/client/src/scripts/mb-admin.ts
> make untrusted till we have figured out perp settling

- Cargo.lock
- client/src/client.rs
- client/src/context.rs
- client/src/health_cache.rs
- liquidator/src/main.rs
- liquidator/src/rebalance.rs
- programs/mango-v4/src/state/orderbook/bookside.rs
- programs/mango-v4/src/state/orderbook/ordertree.rs
- send reduce-only ioc order if possible
- settle pnl if needed
- deactivate position
> Liquidator: reduce perp base pos if possible

- ts/client/src/accounts/mangoAccount.ts
> Fix getAverageEntryPrice so it divides instead of multiplies

- programs/mango-v4/src/state/orderbook/book.rs
> dont process orders which have 0 lots; dont return early, we still want to apply ioc penalty

- client/src/context.rs
- keeper/src/crank.rs
- keeper/src/main.rs
> abort if new tokens or perp markets listed

- ts/client/src/accounts/group.ts
- ts/client/src/scripts/mb-admin.ts
> client support for security admin

- programs/mango-v4/src/error.rs
- programs/mango-v4/src/health/cache.rs
- programs/mango-v4/src/health/client.rs
- programs/mango-v4/src/instructions/group_edit.rs
- programs/mango-v4/src/instructions/token_deposit.rs
- programs/mango-v4/src/lib.rs
- programs/mango-v4/src/state/group.rs
- ts/client/src/client.ts
- ts/client/src/mango_v4.ts
> group level token deposit limit

- programs/mango-v4/src/instructions/perp_edit_market.rs
- programs/mango-v4/src/instructions/serum3_edit_market.rs
- programs/mango-v4/src/instructions/token_edit.rs
I ran an existing test on this branch and on dev, here is the cu result
after
```
[2023-01-23T19:24:57.708009000Z DEBUG solana_runtime::message_processor::stable_log] Program log: Instruction: TokenEdit
[2023-01-23T19:24:57.710337000Z DEBUG solana_runtime::message_processor::stable_log] Program log: Maint asset weight: old - 0.80000001192093, new - 1.0
[2023-01-23T19:24:57.711629000Z DEBUG solana_runtime::message_processor::stable_log] Program log: Init asset weight: old - 0.600000023841858, new - 1.0
[2023-01-23T19:24:57.712943000Z DEBUG solana_runtime::message_processor::stable_log] Program log: Maint liab weight: old - 1.200000047683716, new - 1.0
[2023-01-23T19:24:57.714260000Z DEBUG …
```
> log old and new in edit ixs

- programs/mango-v4/src/instructions/perp_place_order.rs
- programs/mango-v4/src/lib.rs
- programs/mango-v4/src/state/orderbook/book.rs
- ts/client/src/client.ts
- ts/client/src/mango_v4.ts
> return order id from a perp place order ix

- programs/mango-v4/src/instructions/group_edit.rs
> logging + prevention of setting admin to default pk

- programs/mango-v4/src/instructions/perp_liq_base_position.rs
- programs/mango-v4/src/instructions/perp_liq_quote_and_bankruptcy.rs
- programs/mango-v4/src/instructions/perp_settle_pnl.rs
- programs/mango-v4/src/instructions/token_liq_bankruptcy.rs
- programs/mango-v4/src/instructions/token_liq_with_token.rs
Just for safety, the other conditions and borrowing pattern would already make it impossible.
> Add explicit self-liquidation checks

- ts/client/src/client.ts
- ts/client/src/scripts/mb-admin-close.ts
- ts/client/src/scripts/mb-liqtest-create-group.ts
- ts/client/src/scripts/mb-liqtest-make-candidates.ts
- ts/client/src/scripts/mb-liqtest-settle-and-close-all.ts
This allows us to configure a prioritization fee for these calls.
> ts: Use sendAndConfirmTransaction instead of anchor's .rpc()

- Cargo.lock
- cli/Cargo.toml
- client/Cargo.toml
- keeper/Cargo.toml
- liquidator/Cargo.toml
- programs/mango-v4/Cargo.toml
i am having issues in solana-accountsdb-connector when using both mango & openbook, relaxing the requirements here simplifies my life
> update serum to most recent openbook version

- DEVELOPING.md
- README.md
Just documenting how we release, adding some other placeholder documents, please suggest whatever you can think of, we can fill them out later, useful to get outline in imo
> various readme updates

- programs/mango-v4/src/instructions/token_deposit.rs
> fix log amount in token deposit

- ts/client/src/accounts/mangoAccount.ts
- ts/client/src/accounts/perp.ts
> update settle limit before returning settleable pnl

- package.json
- yarn.lock
> upgrade a bunch of ts packages

- programs/mango-v4/src/instructions/account_toggle_freeze.rs
- programs/mango-v4/src/instructions/perp_edit_market.rs
- programs/mango-v4/src/instructions/token_edit.rs
> restrict what a security admin can do

- keeper/src/crank.rs
> dont try to update mngo-perp-old since its in reduce only with no oi

- ts/client/src/accounts/perp.ts
> fix fillevent type in client

- liquidator/src/main.rs
But do exit when one of the core jobs exits.
> Liquidator: don't exit immediately

- programs/mango-v4/src/instructions/serum3_liq_force_cancel_orders.rs
- programs/mango-v4/src/instructions/serum3_place_order.rs
- programs/mango-v4/src/instructions/serum3_settle_funds.rs
- programs/mango-v4/tests/cases/test_serum.rs
- programs/mango-v4/tests/program_test/mod.rs
At least for markets with USDC quote currency.
> Fees buyback: Credit users for ui part of serum fees

- programs/mango-v4/src/instructions/token_liq_with_token.rs
Make name match what is shown in the equations
> Fix comment token_liq_with_token

- bin/keeper/src/taker.rs
- lib/client/src/client.rs
- lib/client/src/context.rs
* create OO
* place order
* cancel all
also removed unneeded result/error return type that was technically dead code
> Expose instruction builders for Openbook

- Cargo.lock
- Cargo.toml
- bin/cli/Cargo.toml
- bin/cli/src/main.rs
- bin/cli/src/test_oracles.rs
- bin/keeper/src/taker.rs
- lib/client/src/client.rs
- lib/client/src/context.rs
- programs/mango-v4/src/state/oracle.rs
This updates our use of pyth oracle accounts to be more in line with what the updated pyth sdk is doing.
> Pyth: Read agg.price or prev_price, depending on staleness

- bin/cli/src/main.rs
- bin/liquidator/src/liquidate.rs
- bin/liquidator/src/rebalance.rs
- bin/liquidator/src/token_swap_info.rs
- bin/liquidator/src/trigger_tcs.rs
- bin/liquidator/src/util.rs
- bin/settler/src/settle.rs
- lib/client/src/client.rs
Previously we only tried a route to USDC with onlyDirectRoutes=true.
> liquidator rebalance: try a full route and route via sol

- mango_v4.json
- programs/mango-v4/src/lib.rs
- programs/mango-v4/src/state/token_conditional_swap.rs
- programs/mango-v4/tests/program_test/mango_client.rs
- ts/client/src/accounts/mangoAccount.ts
- ts/client/src/client.ts
- ts/client/src/mango_v4.ts
Breaks compatibility with the previous tcs_create instruction by adding this flag.
> Tcs: Add price display style enum

- mango_v4.json
- programs/mango-v4/src/instructions/token_conditional_swap_create.rs
- programs/mango-v4/src/instructions/token_conditional_swap_trigger.rs
- programs/mango-v4/src/lib.rs
- programs/mango-v4/src/logs.rs
- programs/mango-v4/src/state/token_conditional_swap.rs
- programs/mango-v4/tests/program_test/mango_client.rs
- ts/client/scripts/liqtest/liqtest-make-tcs-candidates.ts
- ts/client/src/accounts/mangoAccount.ts
- ts/client/src/client.ts
- ts/client/src/mango_v4.ts
This way the ui can know what the user created the tcs order for.
Introduces tcs create and trigger v2 logs.
> Tcs: store a display-only intention enum

- CHANGELOG.md
- programs/mango-v4/src/instructions/account_expand.rs
> Account expansion: Transfer more lamports only if needed

- bin/liquidator/src/main.rs
And reduce the default from 5s to 1s.
> liquidator: Make the check interval configurable

- ts/client/src/client.ts
Previous approach was bad needed to adjust it to what priority fee use
> preprended instruction change

- mango_v4.json
- programs/mango-v4/src/events.rs
- programs/mango-v4/src/health/cache.rs
- programs/mango-v4/src/instructions/compute_account_data.rs
- programs/mango-v4/src/lib.rs
- ts/client/src/client.ts
- ts/client/src/mango_v4.ts
It's used for tests, we don't want people depend on it.
> Drop HealthCache from idl, disable ComputeAccountData ix

- ts/client/src/accounts/bank.ts
> Make getBorrowRateWithoutUpkeepRate() work in more cases

- mango_v4.json
- programs/mango-v4/src/instructions/token_edit.rs
- programs/mango-v4/src/instructions/token_register.rs
- programs/mango-v4/src/instructions/token_register_trustless.rs
- programs/mango-v4/src/instructions/token_update_index_and_rate.rs
- programs/mango-v4/src/lib.rs
- programs/mango-v4/src/logs.rs
- programs/mango-v4/src/state/bank.rs
- programs/mango-v4/tests/program_test/mango_client.rs
- ts/client/src/client.ts
- ts/client/src/clientIxParamBuilder.ts
- ts/client/src/mango_v4.ts
Allows for better configurability independent of the previous MAX_RATE concept
> Bank: store interest curve scale and target util separately

- bin/settler/src/settle.rs
- programs/mango-v4/src/instructions/perp_settle_pnl.rs
- programs/mango-v4/src/state/perp_market.rs
- programs/mango-v4/tests/cases/test_perp_settle.rs
- Only ever give an incentive when pnl is at least 1% of the position value. That way large positions (like $100k in SOL-PERP) don't get settled on 0.1% price fluctuations. The price now needs to change by 1% for settlement to occur.
- For low health incentives, cap the percentual incentive at 2x the flat settle fee. We want to give the settler incentive to use these first, but the settler doesn't take on risk, so the reward doesn't need to be large.
> Change conditions for perp settle incentive

- .github/workflows/ci-code-review-rust.yml
- .github/workflows/ci-code-review-ts.yml
- .github/workflows/ci-labels.yml
Hey! Couple of CI tweaks I thought would improve quality and developer experience
1. Fixes depcheck so it runs on all branches without failing due to missing library
2. Replaces `semgrep` with `CodeQL` as TS static analysis tool (better signal)
3. Removes Trivy reports to the `Security` tab as `Dependabot` is enabled, currently causing warning dupes
> CI updates

- bin/liquidator/src/main.rs
tcs devnet tests want borrow-buy-token
> liquidator: make tcs mode configurable

- mango_v4.json
- programs/mango-v4/src/accounts_ix/serum3_place_order.rs
- programs/mango-v4/src/error.rs
- programs/mango-v4/src/health/cache.rs
- programs/mango-v4/src/instructions/health_region.rs
- programs/mango-v4/src/instructions/ix_gate_set.rs
- programs/mango-v4/src/instructions/serum3_edit_market.rs
- programs/mango-v4/src/instructions/serum3_place_order.rs
- programs/mango-v4/src/instructions/serum3_register_market.rs
- programs/mango-v4/src/instructions/token_register.rs
- programs/mango-v4/src/instructions/token_register_trustless.rs
- programs/mango-v4/src/lib.rs
- programs/mango-v4/src/state/bank.rs
- programs/mango-v4/src/state/group.rs
- programs/mango-v4/src/state/mango_account_components.rs
- programs/mango-v4/src/state/serum3_market.rs
- programs/mango-v4/tests/cases/test_serum.rs
- programs/mango-v4/tests/program_test/mango_client.rs
- ts/client/src/client.ts
- ts/client/src/clientIxParamBuilder.ts
- ts/client/src/mango_v4.ts
- track min bid, max ask
- track maximal token outflow from oo
- add serum3_place_order_v2 with mutable receiver bank
- placing openbook orders is restricted to a certain distance from the oracle
> Openbook token tracking and price bands

- programs/mango-v4/Cargo.toml
- programs/mango-v4/src/allocator.rs
- programs/mango-v4/src/lib.rs
To allow making use of extended heap sizes.
> Use custom allocator for the program

- programs/mango-v4/src/accounts_ix/token_withdraw.rs
- programs/mango-v4/src/error.rs
- programs/mango-v4/src/instructions/token_withdraw.rs
- programs/mango-v4/tests/cases/test_delegate.rs
- programs/mango-v4/tests/cases/test_margin_trade.rs
- programs/mango-v4/tests/program_test/mod.rs
- if they're withdrawing to the owner's ata
- if they're closing the token position
- if the amount is small
> Allow delegates to withdraw small token amounts

- programs/mango-v4/src/health/cache.rs
- programs/mango-v4/src/state/orderbook/bookside.rs
also optimizes heap allocations on health calculation
> helpers for estimating order sizes

- ts/client/scripts/deposit-into.ts
- ts/client/src/client.ts
And add a script for using it.
> ts client: Support deposit-into-existing

- bin/cli/src/test_oracles.rs
- bin/keeper/src/crank.rs
- bin/keeper/src/main.rs
- bin/keeper/src/taker.rs
- bin/liquidator/src/main.rs
- bin/liquidator/src/metrics.rs
- bin/liquidator/src/telemetry.rs
- bin/service-mango-fills/src/main.rs
- bin/service-mango-orderbook/src/main.rs
- bin/settler/src/main.rs
- bin/settler/src/metrics.rs
- lib/client/src/client.rs
- lib/client/src/snapshot_source.rs
- lib/client/src/util.rs
Burst can lead to undesired behavior, in particular with rate limits.
> Switch all tokio Interval to MissedTickBehavior::Delay

- package.json
- ts/client/src/utils/rpc.ts
- yarn.lock
currently there is problem that sometimes tx is confirmed on solana exploler but our confirmation do not confirm this will fix that combination of 3 methods will give good results
> Improve tx confirmation

- programs/mango-v4/src/instructions/serum3_place_order.rs
- programs/mango-v4/tests/cases/test_serum.rs
Previously serum3_place_order would fail when deposit limits were exhausted on the payer token side. Now the failure only happens when payer tokens need to be borrowed.
> deposit limit: always allow obv1-selling deposits

- bin/settler/src/main.rs
- bin/settler/src/settle.rs
- bin/settler/src/tcs_start.rs
in particular: don't panic when a health cache can't be constructed
> Settler: Keep going on error

- programs/mango-v4/tests/cases/mod.rs
- programs/mango-v4/tests/cases/test_basic.rs
- programs/mango-v4/tests/cases/test_borrow_limits.rs
- programs/mango-v4/tests/cases/test_collateral_fees.rs
- programs/mango-v4/tests/cases/test_fees_buyback_with_mngo.rs
- programs/mango-v4/tests/cases/test_force_close.rs
- programs/mango-v4/tests/cases/test_liq_perps_bankruptcy.rs
- programs/mango-v4/tests/cases/test_liq_perps_base_and_bankruptcy.rs
- programs/mango-v4/tests/cases/test_liq_perps_positive_pnl.rs
- programs/mango-v4/tests/cases/test_liq_tokens.rs
- programs/mango-v4/tests/cases/test_margin_trade.rs
- programs/mango-v4/tests/cases/test_perp.rs
- programs/mango-v4/tests/cases/test_perp_settle.rs
- programs/mango-v4/tests/cases/test_perp_settle_fees.rs
- programs/mango-v4/tests/cases/test_serum.rs
- programs/mango-v4/tests/cases/test_token_conditional_swap.rs
- programs/mango-v4/tests/cases/test_token_update_index_and_rate.rs
- programs/mango-v4/tests/program_test/utils.rs
- nicer floating point equality comparisons using macros
- nicer send-tx-and-expect-error calls
> tests: cleanup

- ts/client/src/accounts/mangoAccount.ts
This function was only returning one side of funding, should be summed
> Fix getCumulativeFundingUi

- lib/client/src/swap/sanctum.rs
Taken from https://github.com/igneous-labs/sanctum-lst-list/blob/master/sanctum-lst-list.toml
> liquidator: add more LST for sanctum swap

- bin/liquidator/src/liquidate.rs
- bin/liquidator/src/rebalance.rs
- bin/liquidator/src/telemetry.rs
- bin/liquidator/src/trigger_tcs.rs
- bin/settler/src/tcs_start.rs
- lib/client/src/client.rs
- lib/client/src/swap/jupiter_v6.rs
- lib/client/src/swap/sanctum.rs
It could be the owner or the delegate
> rust client: rename Client::owner to "authority"
